CREATE DATABASE IF NOT EXISTS astro CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'astro'@'localhost' IDENTIFIED BY '5gh6w35';
GRANT ALL ON astro.* TO 'astro'@'localhost';

CREATE TABLE IF NOT EXISTS  `astro`.`star`
(`id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(50) UNIQUE NOT NULL,
 `ra` FLOAT NOT NULL,
 `dec` FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS `astro`.`message`
(
 `id` INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `text` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `astro`.`log`
(
 `id` INTEGER PRIMARY  KEY NOT NULL AUTO_INCREMENT,
 `time` INTEGER DEFAULT NULL,
 `star_id` INTEGER DEFAULT NULL,
 `msg_id` INTEGER DEFAULT NULL,
 `ra` FLOAT DEFAULT NULL,
 `dec` FLOAT DEFAULT NULL,
 `focus` FLOAT DEFAULT NULL,
 `temp_in` FLOAT DEFAULT NULL,
 `temp_out` FLOAT DEFAULT NULL,
 `status` CHAR(10) DEFAULT NULL,
  FOREIGN KEY(`star_id`) REFERENCES `astro`.`star`(`id`),
  FOREIGN KEY(`msg_id`) REFERENCES `astro`.`message`(`id`)
);

